### ISSUE TITLE
Error converting a plugin from 1.20.0 to 2.0.0

### ISSUE THREAD

**Issue by poeticninja** [hapijs/hapi#1337]
I am getting an error on a plugin that worked in 1.20.0 but not on 2.0.0.

Error:

```
Debug: hapi, internal, implementation, error 
    TypeError: Uncaught error: Property 'responses' of object [object Object] is not a function
```

Where do I access the response for plugins. I am needing to modify the response.view.context.

```
 // Hook onto the 'onPostHandler'
plugin.ext('onPostHandler', function (request, next) {
    // Get the response object
    var response = request.response();
   ///other code here
}
```

My plugin https://npmjs.org/package/hapi-named-routes
