### ISSUE TITLE
Typescript error/conflict for static file serving with `@hapi/inert` after updating `@hapi/hapi` from v21.1.0 to v21.2.0

### ISSUE THREAD

**Issue by ceisele-r** [hapijs/hapi#4416]
#### Support plan

* *is this issue currently blocking your project?* (yes/no): no
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: v16.19.0
* *module version with issue*: v21.2.0
* *last module version without issue*: v21.1.0
* *environment* (e.g. node, browser, native): node, happens at compile time/lint
* *used with* (e.g. hapi application, another framework, standalone, ...): standalone
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

After trying to update from `@hapi/hapi` v21.1.0 to v21.2.0, the following Typescript error is emitted:
`Property 'file' does not exist on type 'ResponseToolkit<ReqRefDefaults>'` at the following code line when serving static files (https://hapi.dev/tutorials/servingfiles/?lang=en_US#hfile):

```typescript
    server.route({
        method: 'GET',
        path: '/picture.jpg',
        handler: (request, h) => {
            // Error is emitted here
            return h.file('picture.jpg');
        }
    });
```

#### What was the result you got?
Error `Property 'file' does not exist on type 'ResponseToolkit<ReqRefDefaults>'`

I have a feeling that this resulted from https://github.com/hapijs/hapi/pull/4398 , so I uninstalled `@types/hapi__hapi` and `@types/hapi__inert` but it seems `@hapi/inert` does not (yet?) ship the types itself, therefore `@types/hapi__inert` is still required.
So I reinstalled `@types/hapi__inert` and the error went away but a new error in the inert's type definitions file `node_modules\@types\hapi__inert\index.d.ts` occurred:

It declares
```typescript
    interface ResponseToolkit {
        /**
         * Transmits a file from the file system. The 'Content-Type' header defaults to the matching mime type based on filename extension.
         * @see {@link https://github.com/hapijs/inert#replyfilepath-options}
         */
        file(path: string, options?: inert.ReplyFileHandlerOptions): ResponseObject;
    }
```

but the line declaring file(...) emits the following errors:
```
Cannot find name 'https'
Cannot find name 'ResponseObject'.
```

My guess is that it's because the inert types file only imports `import { Plugin, Request } from '@hapi/hapi';` but should also import `ResponseObject` from `@hapi/hapi` now.
However, this is in DT repo until now.
Are there also plans to move the `inert` types (and probably also `nes` types) also to their repos within `@hapi` and fix this error then?

#### What result did you expect?
No Typescript compile error.

**Comment by kanongil** [comment]
I hit this issue as well.

While it seems related, I don't think #4415 solves this, as it doesn't change the visibility of `ResponseObject`.

**Comment by kanongil** [comment]
For anyone looking into this…

The DT hapi types exports `ResponseObject` here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f28f2a092cda27550a04e912bc81ba6d139c45b4/types/hapi__hapi/index.d.ts#L724

The DT inert types uses it here, without an import: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/f206038074aad810400799206392e2a674b8ed74/types/hapi__inert/index.d.ts#L164.

**Comment by kanongil** [comment]
This should be resolved with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64151 and the newly released `@types/hapi__inert@5.2.5`.

Can you verify that it also works for you @ceisele-r?

**Comment by devinivy** [comment]
Thanks to both of you for wrangling this 👍 Hoping that does that trick.

**Comment by ceisele-r** [comment]
Thank you @kanongil and @devinivy , I can confirm updating to `@hapi/hapi@21.2.1` and `@types/hapi__inert@5.2.5` works and resolves this issue 👍
