### ISSUE TITLE
Updating from 16.4.3 to 16.5.0:  Podium.decorate is not a function error

### ISSUE THREAD

**Issue by SanderElias** [hapijs/hapi#3552]
#### Are you sure this is an issue with hapi or are you just looking for some help?
I'm not entierly sure this issue is originating from hapi itself, but when I update to 16.5.0 and I do a request, I get this error:
```
/.../node_modules/hapi/lib/request.js:63
    Podium.decorate(this, internals.emitter);
           ^
TypeError: Podium.decorate is not a function
    at new internals.Request (/.../node_modules/hapi/lib/request.js:63:12)
    at module.exports.internals.Generator.internals.Generator.request (/.../node_modules/hapi/lib/request.js:32:21)
    at Server.<anonymous> (/.../node_modules/hapi/lib/connection.js:260:48)
    at emitTwo (events.js:125:13)
    at Server.emit (events.js:213:7)
    at parserOnIncoming (_http_server.js:602:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
 ```
(I replaced the long path tih ... for readability)

#### What are you trying to achieve or the steps to reproduce?
`yarn add hapi@16.5.0` introduces the problem.
`yarn add hapi@16.4.3` resolved the issue.

I repeated the steps a couple of times, and it is really the upgrade of hapi that triggers the issue.

* *node version*: 8.2.0
* *hapi version*: 16.5.0
* *os*: ubuntu 16.04

**Comment by Marsup** [comment]
No issue with npm here, try to wipe your dependencies and reinstall, it looks like a yarn or local issue.

**Comment by Boelensman1** [comment]
I have this issue as well, have reinstalled a few times now with no change in the behaviour

**Comment by uzysjung** [comment]
me too,
hapi 16 , node 6.9.5 , centos6

**Comment by fabiob** [comment]
#3542 only updates `npm-shrinkwrap.json`. `package.json` still points to `"podium": "1.x.x"`.

So it looks like a packaging bug to me.

**Comment by hueniverse** [comment]
I am not seeing the issue and I do not support yarn (in that I do not test deployments with it or use it).

**Comment by SanderElias** [comment]
@hueniverse Ok, that's fair. But the issue @fabiob pointed at, can you still make that change? It would solve it, and make the package.json more in sync with what is actually needed.

**Comment by nrn** [comment]
I know it's pretty edge case, but this error also happens with npm@5.3.0 if you have a project that has two different deps that rely on hapi, and one uses 16.3 and the other uses 16.5.

**Comment by kanongil** [comment]
@nrn Your issue is likely due to using `package-lock=false` (See https://github.com/hapijs/hapi/issues/3556).

**Comment by nrn** [comment]
@kanongil Unfortunately we do use the lock file, and haven't turned that setting off.

**Comment by nrn** [comment]
Thanks for fixing this @hueniverse!

**Comment by barbalex** [comment]
this happens to me with:

- macOS 10.12.6
- node 8.4
- npm 5.3.0
- hapi 16.5.2

**Comment by ArsalanDotMe** [comment]
Can confirm that on npm 5.x, somehow podium 1.2.5 is installed even with hapijs 16.5.2. Can we have a patch in hapi v16 that explicitly sets the version for podium?

**Comment by mathiasbynens** [comment]
Seeing the same issue.

```
$ npm list hapi
npm list jsperf.com@2.0.0 ~/projects/jsperf.com
├─┬ glue@4.2.0
│ └── hapi@16.6.2  deduped
└── hapi@16.6.2

$ npm list podium
jsperf.com@2.0.0 ~/projects/jsperf.com
└─┬ hapi@16.6.2
  └── podium@1.2.5
```

**Comment by mathiasbynens** [comment]
`rm -rf node_modules && rm package-lock.json && npm install` helped in our case.
