### ISSUE TITLE
Joi 2.0 integration feedback

### ISSUE THREAD

**Issue by hueniverse** [hapijs/hapi#1134]
Please try adding `Hapi.joi.version('v2')` when you first load hapi and see how your validation rules work with the new joi 2.0 module. Any issues or feedback would be greatly appreciated. At some point we'll publish a hapi 2.0 with joi 2.0 as the default based on this feedback.

**Comment by jbarros35** [comment]
Error: Cannot find module 'joi'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\jlopesde\node\express\myapp\routes.js:2:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by Marsup** [comment]
@jbarros35 do you plan to keep on posting completely out of context stack traces in random issues that have nothing to do with it ?
