### ISSUE TITLE
Broken typings when upgrading to 21.4.0

### ISSUE THREAD

**Issue by svrnwnsch** [hapijs/hapi#4547]
### Runtime

node.js

### Runtime version

22.15.1

### Module version

21.4.0

### Last module version without issue

21.3.12

### What are you trying to achieve or the steps to reproduce?

We have handle who look simplified like this:

```
export const create = ():RouteOptions => ({
  handler: async (req: Request<{ Payload: { from: string; to: string; } }>, h: ResponseToolkit): Promise<ResponseObject> => {
    const from = req.payload.from
    const to = req.payload.to
    .....
    await someFunction(req);

    return h.response().code(201);
  },
});

export const someFunction = async (request: Request): Promise<void> => ({
   .....
})
```

### What was the result you got?

I get a typescript error:

```
error TS2345: Argument of type 'Request<{ Payload: { from: string; to: string; }; }>' is not assignable to parameter of type 'Request<ReqRefDefaults>'.
  The types of 'route.settings.pre' are incompatible between these types.
    Type 'RouteOptionsPreArray<{ Payload: { from: string; to: string; }; }> | undefined' is not assignable to type 'RouteOptionsPreArray<ReqRefDefaults> | undefined'.
      Type 'RouteOptionsPreArray<{ Payload: { from: string; to: string; }; }>' is not assignable to type 'RouteOptionsPreAllOptions<ReqRefDefaults>[]'.
        Type 'RouteOptionsPreAllOptions<{ Payload: { from: string; to: string; }; }>' is not assignable to type 'RouteOptionsPreAllOptions<ReqRefDefaults>'.
          Type 'Method<{ Payload: { from: string; to: string; }; }, ReturnValue<{ Payload: { from: string; to: string; }; }>>' is not assignable to type 'RouteOptionsPreAllOptions<ReqRefDefaults>'.
            Type 'Method<{ Payload: { from: string; to: string; }; }, ReturnValue<{ Payload: { from: string; to: string; }; }>>' is not assignable to type 'Method<ReqRefDefaults, ReturnValue<ReqRefDefaults>>'.
              Types of parameters 'request' and 'request' are incompatible.
                Type 'Request<ReqRefDefaults>' is not assignable to type 'Request<{ Payload: { from: string; to: string; }; }>'.
                  Types of property 'payload' are incompatible.
                    Type 'string | object | Readable | Buffer<ArrayBufferLike>' is not assignable to type '{ from: string; to: string; }'.
                      Type 'string' is not assignable to type '{ from: string; to: string; }'.

```

To fix this problem I need to change:

```
export const someFunction = async (request: Request<{ Payload: { from: string; to: string; } }>): Promise<void> => ({
   .....
})
```

but this does not work out if `someFunction` is used by different handler with different payloads.

### What result did you expect?

keep it the way as in 21.3.12 an not have an error here.

**Comment by damusix** [comment]
@svrnwnsch you might want to try using generics instead. `someFunc = <R extends Request<any>> (req: R) => {...}` so typescript matches any request type instead of a specific request type.

**Comment by damusix** [comment]
@svrnwnsch Can you try with the 21.4.5 release? LMK how it behaves given your use case.
